[package]
name = "DeityGB"
version = "0.1.0"
authors = ["jason"]
edition = "2018"
default-run = "DeityGB"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

# Keeping here for future reference in case it's needed

#[patch.crates-io]
#macroquad = { path = "macroquad" }  # Adjust path to where you cloned it

[dependencies]
macroquad = "=0.4.0"
csv = "1.3.1"
cpal = "0.16"
image = { version = "0.24.9", default-features = false, features = ["png"] }

[target.'cfg(target_os = "macos")'.dependencies]
objc = "0.2.7"

[lib]
name = "deitygb"
path = "src/lib.rs"

[[bin]]
name = "DeityGB"
path = "src/main.rs"

[[bin]]
name = "gb-headless"
path = "src/bin/gb-headless.rs"
